In [1]:
import nltk

In [3]:
nltk.download

<bound method Downloader.download of <nltk.downloader.Downloader object at 0x000001D4C086D648>>

In [ ]:
#Tokenisation

In [3]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [4]:
my_txt = "Hello Mr. Learners, how is learning going on? Hope things are fine. Hope the lockdown solves all the issues."

In [5]:
sent_tokenize(my_txt)

['Hello Mr. Learners, how is learning going on?',
 'Hope things are fine.',
 'Hope the lockdown solves all the issues.']

In [6]:
word_tokenize(my_txt)

['Hello',
 'Mr.',
 'Learners',
 ',',
 'how',
 'is',
 'learning',
 'going',
 'on',
 '?',
 'Hope',
 'things',
 'are',
 'fine',
 '.',
 'Hope',
 'the',
 'lockdown',
 'solves',
 'all',
 'the',
 'issues',
 '.']

In [8]:
from nltk.stem import PorterStemmer

In [9]:
ps = PorterStemmer()

In [10]:
words = ['runs','running','run','runner']

In [11]:
for word in words:
    print(ps.stem(word))

run
run
run
runner


In [12]:
text_data = ['I runs verying is fast','I was very running fast veries veried']

In [13]:
import pandas as pd

c:\users\sanu menon\appdata\local\programs\python\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [15]:
df = pd.DataFrame({'Text':text_data})
df

Text
0                 I runs verying is fast
1  I was very running fast veries veried

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv = CountVectorizer()

In [19]:
def f(text):
    words = word_tokenize(text)
    res = []
    for word in words:
        res.append(ps.stem(word))
    return (' '.join(res))

df.Text = df.Text.map(f)

In [20]:
df.Text

0              I run veri is fast
1    I wa veri run fast veri veri
Name: Text, dtype: object

In [23]:
cv.fit_transform(df.Text).toarray()

array([[1, 1, 1, 1, 0],
       [1, 0, 1, 3, 1]], dtype=int64)

In [22]:
cv.vocabulary_

{'run': 2, 'veri': 3, 'is': 1, 'fast': 0, 'wa': 4}

In [25]:
from nltk.stem import WordNetLemmatizer

In [26]:
wl = WordNetLemmatizer()

In [27]:
wl.lemmatize('better',pos = 'a')

'good'

In [28]:
wl.lemmatize('best',pos = 'a')

'best'

In [29]:
from nltk.stem import LancasterStemmer

In [30]:
ls = LancasterStemmer()

In [31]:
ls.stem('better')

'bet'

In [32]:
text = 'He was running and eating at the, same time. He also has a very bad habbit of playing in the Sun after having food?'

In [ ]:
punctuations = ',.?'

In [33]:
text = text.replace(',','').replace('.','').replace('?','')
text

'He was running and eating at the same time He also has a very bad habbit of playing in the Sun after having food'

In [36]:
words = word_tokenize(text)
words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'the',
 'same',
 'time',
 'He',
 'also',
 'has',
 'a',
 'very',
 'bad',
 'habbit',
 'of',
 'playing',
 'in',
 'the',
 'Sun',
 'after',
 'having',
 'food']

In [37]:
for word in words:
    print(wl.lemmatize(word,pos = 'v'))#verb

He
be
run
and
eat
at
the
same
time
He
also
have
a
very
bad
habbit
of
play
in
the
Sun
after
have
food


In [51]:
horror_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/horror-train.csv')

In [52]:
horror_data.columns

Index(['id', 'text', 'author'], dtype='object')

In [53]:
horror_data = horror_data[['text']]

In [54]:
horror_data[:5]

text
0  This process, however, afforded me no means of...
1  It never once occurred to me that the fumbling...
2  In his left hand was a gold snuff box, from wh...
3  How lovely is spring As we looked from Windsor...
4  Finding nothing else, not even gold, the Super...

In [55]:
def f(text):
    return text.replace(',','').replace('?','').replace('.','')
horror_data['new_text'] = horror_data.text.map(f)
horror_data['new_text'][:5]

0    This process however afforded me no means of a...
1    It never once occurred to me that the fumbling...
2    In his left hand was a gold snuff box from whi...
3    How lovely is spring As we looked from Windsor...
4    Finding nothing else not even gold the Superin...
Name: new_text, dtype: object

In [59]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [62]:
def stem_f(new_text):
    words = word_tokenize(new_text)
    sent=[]
    for word in words:
        sent.append(ps.stem(word))
    return (' '.join(sent))
horror_data['stem_words'] = horror_data.new_text.map(stem_f)

In [63]:
horror_data['stem_words'][:10]

0    thi process howev afford me no mean of ascerta...
1    It never onc occur to me that the fumbl might ...
2    In hi left hand wa a gold snuff box from which...
3    how love is spring As we look from windsor ter...
4    find noth els not even gold the superintend ab...
5    A youth pass in solitud my best year spent und...
6    the astronom perhap at thi point took refug in...
7             the surcingl hung in riband from my bodi
8    I knew that you could not say to yourself 'ste...
9    I confess that neither the structur of languag...
Name: stem_words, dtype: object

In [69]:
cv = CountVectorizer(stop_words='english')

In [70]:
cv.fit(horror_data.text)
len(cv.vocabulary_)

24764

In [71]:
cv.fit(horror_data.stem_words)
len(cv.vocabulary_)

15355

In [73]:
out = cv.transform(horror_data.stem_words)

In [74]:
from sklearn.neighbors import NearestNeighbors

In [75]:
nn = NearestNeighbors(metric='cosine')

In [76]:
nn.fit(out)

NearestNeighbors(metric='cosine')

In [77]:
nn.kneighbors(out[:1])

(array([[6.66133815e-16, 6.75557158e-01, 6.75557158e-01, 6.92206494e-01,
         7.19024257e-01]]),
 array([[    0,  8578, 19095,   803, 18573]], dtype=int64))

In [79]:
horror_data.text[0]

'This process, however, afforded me no means of ascertaining the dimensions of my dungeon; as I might make its circuit, and return to the point whence I set out, without being aware of the fact; so perfectly uniform seemed the wall.'

In [86]:
horror_data.iloc[8578]

text          Much, however, might be ascertained.
new_text         Much however might be ascertained
stem_words           much howev might be ascertain
Name: 8578, dtype: object

In [81]:
horror_data.text[19095]

'Now this is the point.'

In [82]:
horror_data.text[803]

'But, in fact, this is a point of minor importance.'

In [83]:
horror_data.text[18573]

'This latter point, however, was fully disproved.'