In [2]:
from sklearn.datasets import california_housing

In [7]:
from sklearn.linear_model import LinearRegression

In [4]:
house_data = california_housing.fetch_california_housing()

In [5]:
feature_data = house_data.data
target_data = house_data.target

current_feature_data = feature_data[:-5]
current_target_data = target_data[:-5]

new_feature_data = feature_data[-5:]
new_target_data = target_data[-5:]

In [8]:
lr = LinearRegression()

In [9]:
lr.fit(current_feature_data, current_target_data)

LinearRegression()

In [10]:
lr.coef_

array([ 4.36698295e-01,  9.44056975e-03, -1.07268396e-01,  6.44960409e-01,
       -3.92823742e-06, -3.78591131e-03, -4.21718526e-01, -4.34859339e-01])

In [11]:
lr.fit(new_feature_data, new_target_data)

LinearRegression()

In [12]:
lr.coef_

array([-1.25982639e-01, -2.09113671e-02, -1.62817519e-02, -1.52094168e-02,
        6.80123634e-05,  4.74835543e-02,  1.15604694e-02,  3.51442814e-02])

In [13]:
from sklearn.linear_model import SGDRegressor

In [14]:
sgd_lr = SGDRegressor()

In [15]:
sgd_lr.fit(current_feature_data, current_target_data)

SGDRegressor()

In [17]:
sgd_lr.coef_

array([ 2.76336359e+11,  1.89113372e+11, -1.25032783e+11, -4.74153385e+09,
        3.22348761e+11, -5.32520237e+11, -1.38834645e+11, -1.64863579e+11])

In [18]:
sgd_lr.partial_fit(new_feature_data, new_target_data)

SGDRegressor()

In [19]:
sgd_lr.coef_

array([ 2.75378884e+11,  1.81293593e+11, -1.26948324e+11, -5.17141557e+09,
        4.86574240e+10, -5.33775073e+11, -1.51698110e+11, -1.25438983e+11])

Limitations of Online Learning Models

    Doesn't support pipeline

In [20]:
import pandas as pd

c:\users\sanu menon\appdata\local\programs\python\python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [23]:
data= pd.read_csv('E:\Deepthi\Edyoda\data-science-complete-tutorial-master\Data\Amazon_reviews\Reviews.csv',nrows=10000,usecols=['Score','Text'])

In [24]:
data.head()

Score                                               Text
0      5  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      4  This is a confection that has been around a fe...
3      2  If you are looking for the secret ingredient i...
4      5  Great taffy at a great price.  There was a wid...

In [25]:
from sklearn.feature_extraction.text import HashingVectorizer

In [26]:
hv = HashingVectorizer(n_features=1000)

In [27]:
hv.partial_fit(data.Text)

HashingVectorizer(n_features=1000)

In [28]:
hv.transform(data.Text[:5]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [30]:
mnb= MultinomialNB()

In [31]:
data_itr = pd.read_csv('E:\Deepthi\Edyoda\data-science-complete-tutorial-master\Data\Amazon_reviews\Reviews.csv',chunksize=1000,usecols=['Score','Text'])

In [34]:
hv = HashingVectorizer(n_features=1000)
mnb = MultinomialNB()

for data in data_itr:
    hv.partial_fit(data.Text)
    feature = hv.transform(data.Text)
    feature = np.abs(feature)
    mnb.partial_fit(feature,data.Score,[1,2,3,4,5])

In [35]:
feature = hv.transform(data.Text[:5])
feature = np.abs(feature)
mnb.predict(feature)

array([5, 5, 5, 5, 5])